import { GridColDef, GridValueGetterParams } from "@material-ui/data-grid";


export const columns: GridColDef[] = [
    { field: 'id', headerName: 'ID', width: 100 },
    // ID and matricule should be different and matricule
    // is generated by the server. For now it's absent so we use ID
    // to simulate it
    {
      field: 'matricule',
      headerName: 'Matricule',
      width: 150,
      editable: true,
    },
    {
      field: 'full_name',
      headerName: 'Full Names',
      description: 'This column has a value getter and is not sortable.',
      sortable: false,
      width: 200,
      valueGetter: (params: GridValueGetterParams) =>
        `${params.getValue(params.id, 'first_name') || ''} ${
          params.getValue(params.id, 'last_name') || ''
        }`,
    },
    {
        field: 'date_of_birth',
        headerName: 'Date of birth',
        width: 150,
        editable: true,
    },
    {
        field: 'gender',
        headerName: 'Gender',
        width: 130,
        editable: true,
    },
    {
        field: 'fathers_name',
        headerName: `Father's Name`,
        width: 170,
        editable: true,
    },
    {
        field: 'fathers_phone',
        headerName: `Father's Contact`,
        width: 200,
        editable: true,
    },
  ];