export { studentsRouter } from "./studentsRoutes";
export { classesRouter } from "./classesRoute";
export { classListsRouter } from "./classListRoutes";
export { subjectsRouter } from "./subjectsRoute";
export { usersRouter } from "./usersRoutes";
export { marksRouter } from "./marksRoutes";
export { loginRouter } from "./login";
export { teachersRouter } from "./teachersRoutes";
export { sequencesRouter } from "./sequenceRoutes";
