import type { NextPage } from 'next';
import Head from 'next/head';
import { theme } from '../theme';
import { ThemeProvider } from '@material-ui/styles';
import { Typography, Button } from '@material-ui/core';
import Layout from 'components/Layout';

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <Layout>
        <div>
          <Head>
            <title>SchoolX | Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <Typography variant="h6" color="primary">
              Welcome to SchoolX App
            </Typography>
            <Button variant="contained" color="secondary">Create</Button>

          </main>

          <footer>
            <Typography>
              Copyright &copy; 2021
            </Typography>
          </footer>
        </div>
      </Layout>
      
    </ThemeProvider>
  )
}

export default Home
