import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '/Users/rickysaka/Desktop/Work_Desk/SchoolX/styles/Home.module.scss';
import { theme } from '../theme';
import { ThemeProvider } from '@material-ui/styles';
import { Typography, Button } from '@material-ui/core';
import Layout from '../components/Layout';

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <Layout>
        <div className={styles.container}>
          <Head>
            <title>SchoolX | Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <Typography variant="h1" color="primary">
              Welcome to SchoolX App
            </Typography>
            <Button variant="contained" color="secondary">Create</Button>

          </main>

          <footer className={styles.footer}>
            <Typography>
              Copyright &copy; 2021
            </Typography>
          </footer>
        </div>
      </Layout>
      
    </ThemeProvider>
  )
}

export default Home
