import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '/styles/Home.module.scss';

import { Typography, Button } from '@material-ui/core';

const Home: NextPage = () => {
  return (
      <div className={styles.container}>
        <Head>
          <title>SchoolX | Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Typography variant="h6" color="primary">
            Welcome to SchoolX App
          </Typography>
          <Button variant="contained" color="secondary">Create</Button>

        </main>

        <footer className={styles.footer}>
          <Typography>
            Copyright &copy; 2021
          </Typography>
        </footer>
      </div>      
  )
}

export default Home
