import { GridColDef, GridValueGetterParams } from "@material-ui/data-grid";

export const columns: GridColDef[] = [
	{ field: "id", headerName: "ID", width: 100 },
	// ID and matricule should be different and matricule
	// is generated by the server. For now it's absent so we use ID
	// to simulate it
	{
		field: "id",
		headerName: "Matricule",
		width: 150,
		editable: true,
	},
	{
		field: "fullName",
		headerName: "Full Names",
		description: "This column has a value getter and is not sortable.",
		sortable: false,
		width: 200,
		valueGetter: (params: GridValueGetterParams) =>
			`${params.getValue(params.id, "firstName") || ""} ${
				params.getValue(params.id, "lastName") || ""
			}`,
	},
	{
		field: "dateOfBirth",
		headerName: "Date of birth",
		width: 150,
		editable: true,
	},
	{
		field: "gender",
		headerName: "Gender",
		width: 130,
		editable: true,
	},
	{
		field: "fathersName",
		headerName: `Father's Name`,
		width: 170,
		editable: true,
	},
	{
		field: "fathersPhone",
		headerName: `Father's Contact`,
		width: 200,
		editable: true,
	},
];
